openapi: 3.0.0
info:
  title: My User API
  version: 1.0.0
  description: API per la gestione e registrazione degli utenti
servers:
  - url: http://localhost:3000
    description: Server di Sviluppo
tags:
  - name: Authentication
    description: Operazioni relative alla registrazione e autenticazione
  - name: Admin
    description: Operazioni amministrative sugli utenti
  - name: Testing
    description: Endpoint di test per verificare lo stato del servizio

paths:
  /user/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Creates a new user account in the system using a username and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: mario.rossi
                password:
                  type: string
                  example: password123
      responses:
        '201':
          description: User successfully registered.
        '500':
          description: Internal server error.

  /user/test:
    get:
      tags:
        - Testing
      summary: Test endpoint
      description: Returns a success message to verify that the service is up and running.
      responses:
        '201':
          description: Test executed successfully.
          content:
            text/plain:
              schema:
                type: string
                example: Test successfully
        '500':
          description: Internal server error.

  /user/{username}:
    delete:
      tags:
        - Admin
      summary: Delete a household user
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
          description: Username of the household user to delete
      responses:
        '204':
          description: User successfully deleted.
        '404':
          description: User not found.
        '400':
          description: Bad request.
        '500':
          description: Internal server error.
